export const metrics = {
  smallest: '3px',
  small: '5px',
  base: '10px',
  large: '20px',
  largest: '40px',
  inputHeight: '60px',
  inputWidthBase: '200px',
  inputWidthLarge: '400px',
  buttonHeight: '60px',
  radiusBase: '4px',
  radiusLarge: '20px',
  radiusRounded: '50px',
  borderWidth: '1px',
};
